version: '3.3'

services:
  clickhouse-zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
      - "2182:2182"
    container_name: clickhouse-zookeeper
    hostname: clickhouse-zookeeper
    volumes:
      - /shared/ch/zookeeper/data:/data
      - /shared/ch/zookeeper/datalog:/datalog
      - /shared/ch/zookeeper/logs:/logs
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    hostname: clickhouse-kafka
    container_name: clickhouse-kafka
    ports:
      - 9092:9092
    volumes:
      - /shared/ch/kafka/kafka:/kafka
      - /shared/ch/kafka/logs:/tmp/kafka-logs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: DOCKER_NET://localhost:9093,HOST_NET://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_NET:PLAINTEXT,HOST_NET:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_NET
      KAFKA_LISTENERS: DOCKER_NET://localhost:9093,HOST_NET://localhost:9092
      KAFKA_CREATE_TOPICS: "MyTopic:1:1"
    depends_on:
      - "clickhouse-zookeeper"

  clickhouse-01:
    image: yandex/clickhouse-server
    hostname: clickhouse-01
    container_name: clickhouse-01
    ports:
      - 9001:9000
    volumes:
      - ./configuration/config.xml:/etc/clickhouse-server/config.xml
      - ./configuration/macroses/macros-01.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configuration/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./configuration/users.xml:/etc/clickhouse-server/users.xml
      - /shared/ch/clickhouse/log/ch1:/var/log/clickhouse-server
      - /shared/ch/clickhouse/data/ch1:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "clickhouse-zookeeper"

  clickhouse-02:
    image: yandex/clickhouse-server
    hostname: clickhouse-02
    container_name: clickhouse-02
    ports:
      - 9002:9000
    volumes:
      - ./configuration/config.xml:/etc/clickhouse-server/config.xml
      - ./configuration/macroses/macros-02.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configuration/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./configuration/users.xml:/etc/clickhouse-server/users.xml
      - /shared/ch/clickhouse/log/ch2:/var/log/clickhouse-server
      - /shared/ch/clickhouse/data/ch2:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "clickhouse-zookeeper"

  clickhouse-03:
    image: yandex/clickhouse-server
    hostname: clickhouse-03
    container_name: clickhouse-03
    ports:
      - 9003:9000
    volumes:
      - ./configuration/config.xml:/etc/clickhouse-server/config.xml
      - ./configuration/macroses/macros-03.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configuration/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./configuration/users.xml:/etc/clickhouse-server/users.xml
      - /shared/ch/clickhouse/log/ch3:/var/log/clickhouse-server
      - /shared/ch/clickhouse/data/ch3:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "clickhouse-zookeeper"

  clickhouse-04:
    image: yandex/clickhouse-server
    hostname: clickhouse-04
    container_name: clickhouse-04
    ports:
      - 9004:9000
    volumes:
      - ./configuration/config.xml:/etc/clickhouse-server/config.xml
      - ./configuration/macroses/macros-04.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configuration/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./configuration/users.xml:/etc/clickhouse-server/users.xml
      - /shared/ch/clickhouse/log/ch4:/var/log/clickhouse-server
      - /shared/ch/clickhouse/data/ch4:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "clickhouse-zookeeper"

  clickhouse-05:
    image: yandex/clickhouse-server
    hostname: clickhouse-05
    container_name: clickhouse-05
    ports:
      - 9005:9000
    volumes:
      - ./configuration/config.xml:/etc/clickhouse-server/config.xml
      - ./configuration/macroses/macros-05.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configuration/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./configuration/users.xml:/etc/clickhouse-server/users.xml
      - /shared/ch/clickhouse/log/ch5:/var/log/clickhouse-server
      - /shared/ch/clickhouse/data/ch5:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "clickhouse-zookeeper"

  clickhouse-06:
    image: yandex/clickhouse-server
    hostname: clickhouse-06
    container_name: clickhouse-06
    ports:
      - 9006:9000
    volumes:
      - ./configuration/config.xml:/etc/clickhouse-server/config.xml
      - ./configuration/macroses/macros-06.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./configuration/metrika.xml:/etc/clickhouse-server/metrika.xml
      - ./configuration/users.xml:/etc/clickhouse-server/users.xml
      - /shared/ch/clickhouse/log/ch6:/var/log/clickhouse-server
      - /shared/ch/clickhouse/data/ch6:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      - "clickhouse-zookeeper"
networks:
  default:
    external:
      name: clickhouse-net